<?php 
class WCST_Email
{
	public function __construct()
	{
	}
	
	public function force_status_email_sending($action, $order)
	{
		// Ensure gateways are loaded in case they need to insert data into the emails
		WC()->payment_gateways();
		WC()->shipping();

		// Load mailer
		$mailer = WC()->mailer();

		$email_to_send = str_replace( 'send_email_', '', $action );

		$mails = $mailer->get_emails();

		if ( ! empty( $mails ) ) {
			foreach ( $mails as $mail ) {
				if ( $mail->id == $email_to_send ) {
					$mail->trigger( $order->id );
					//$order->add_order_note( sprintf( __( '%s email notification manually sent.', 'woocommerce' ), $mail->title ), false, true );
				}
			}
		}
	}
	function send_error_email_to_admin($text)
	{
		$mail = WC()->mailer();
		$email_heading = get_bloginfo('name');
		$subject = __('Something needs your attention...', 'woocommerce-shipping-tracking');
		
		ob_start();
		$mail->email_header($email_heading );
		_e('<h2>The following error has been generated by your site:</h2>', 'woocommerce-shipping-tracking');
		echo "<p>".$text."</p>";
		$mail->email_footer();
		$message =  ob_get_contents();
		ob_end_clean(); 
		
		
		$mail->send( get_bloginfo('admin_email'), $subject, $message, "Content-Type: text/html\r\n");
	}
}